#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : inkscape
Version  : 0.92.4
Release  : 7
URL      : https://gitlab.com/inkscape/inkscape/-/archive/INKSCAPE_0_92_4/inkscape-INKSCAPE_0_92_4.tar.bz2
Source0  : https://gitlab.com/inkscape/inkscape/-/archive/INKSCAPE_0_92_4/inkscape-INKSCAPE_0_92_4.tar.bz2
Summary  : Professional vector graphics editor
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1
Requires: inkscape-bin = %{version}-%{release}
Requires: inkscape-data = %{version}-%{release}
Requires: inkscape-license = %{version}-%{release}
Requires: inkscape-locales = %{version}-%{release}
Requires: inkscape-man = %{version}-%{release}
BuildRequires : ImageMagick
BuildRequires : ImageMagick-dev
BuildRequires : aspell-dev
BuildRequires : atkmm-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan
BuildRequires : buildreq-gnome
BuildRequires : cairo-dev
BuildRequires : dbus-dev
BuildRequires : gettext
BuildRequires : glibmm-dev
BuildRequires : gtkmm2-dev
BuildRequires : gtkmm3-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : lcms2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libwpg-dev
BuildRequires : lxml
BuildRequires : pango-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(atomic_ops)
BuildRequires : pkgconfig(bdw-gc)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-pdf)
BuildRequires : pkgconfig(cairo-svg)
BuildRequires : pkgconfig(cairomm-1.0)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(gdk-3.0)
BuildRequires : pkgconfig(gdkmm-2.4)
BuildRequires : pkgconfig(gdkmm-3.0)
BuildRequires : pkgconfig(gdl-3.0)
BuildRequires : pkgconfig(giomm-2.4)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(glibmm-2.4)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gsl)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtkmm-2.4)
BuildRequires : pkgconfig(gtkmm-3.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libcdr-0.1)
BuildRequires : pkgconfig(libexif)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(libvisio-0.1)
BuildRequires : pkgconfig(libwpg-0.3)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(libxslt)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangoft2)
BuildRequires : pkgconfig(sigc++-2.0)
BuildRequires : pkgconfig(x11)
BuildRequires : popt-dev
BuildRequires : potrace-dev
Patch1: inkscape-python2.patch

%description
Inkscape is professional quality vector graphics software which runs on
Windows, Mac OS X and GNU/Linux. It is used by design professionals and
hobbyists worldwide, for creating a wide variety of graphics such as
illustrations, icons, logos, diagrams, maps and web graphics. Inkscape uses the
W3C open standard SVG (Scalable Vector Graphics) as its native format, and is
free and open-source software.

%package bin
Summary: bin components for the inkscape package.
Group: Binaries
Requires: inkscape-data = %{version}-%{release}
Requires: inkscape-license = %{version}-%{release}

%description bin
bin components for the inkscape package.


%package data
Summary: data components for the inkscape package.
Group: Data

%description data
data components for the inkscape package.


%package license
Summary: license components for the inkscape package.
Group: Default

%description license
license components for the inkscape package.


%package locales
Summary: locales components for the inkscape package.
Group: Default

%description locales
locales components for the inkscape package.


%package man
Summary: man components for the inkscape package.
Group: Default

%description man
man components for the inkscape package.


%prep
%setup -q -n inkscape-INKSCAPE_0_92_4
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569631158
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static --disable-poppler-cairo \
--disable-strict-build
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1569631158
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/inkscape
cp CMakeScripts/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/inkscape/CMakeScripts_COPYING-CMAKE-SCRIPTS
cp COPYING %{buildroot}/usr/share/package-licenses/inkscape/COPYING
cp GPL2.txt %{buildroot}/usr/share/package-licenses/inkscape/GPL2.txt
cp cxxtest/COPYING %{buildroot}/usr/share/package-licenses/inkscape/cxxtest_COPYING
cp src/libvpsc/COPYING %{buildroot}/usr/share/package-licenses/inkscape/src_libvpsc_COPYING
%make_install
%find_lang inkscape

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/inkscape
/usr/bin/inkview

%files data
%defattr(-,root,root,-)
/usr/share/appdata/inkscape.appdata.xml
/usr/share/applications/inkscape.desktop
/usr/share/icons/hicolor/16x16/apps/inkscape.png
/usr/share/icons/hicolor/22x22/apps/inkscape.png
/usr/share/icons/hicolor/24x24/apps/inkscape.png
/usr/share/icons/hicolor/256x256/apps/inkscape.png
/usr/share/icons/hicolor/32x32/apps/inkscape.png
/usr/share/icons/hicolor/48x48/apps/inkscape.png
/usr/share/inkscape/attributes/README
/usr/share/inkscape/attributes/css_defaults
/usr/share/inkscape/attributes/cssprops
/usr/share/inkscape/attributes/svgprops
/usr/share/inkscape/branding/README
/usr/share/inkscape/branding/inkscape-flat.svg
/usr/share/inkscape/branding/inkscape-text.svg
/usr/share/inkscape/branding/inkscape.svg
/usr/share/inkscape/branding/sodipodi.svg
/usr/share/inkscape/branding/tux.svg
/usr/share/inkscape/examples/README
/usr/share/inkscape/examples/animated-clock.svg
/usr/share/inkscape/examples/art-nouveau-P3.svg
/usr/share/inkscape/examples/blend_modes.svg
/usr/share/inkscape/examples/car.svgz
/usr/share/inkscape/examples/data_uri.svg
/usr/share/inkscape/examples/eastern-motive-P4G.svg
/usr/share/inkscape/examples/filters.svg
/usr/share/inkscape/examples/flow-go.svg
/usr/share/inkscape/examples/flowsample.svg
/usr/share/inkscape/examples/gallardo.svgz
/usr/share/inkscape/examples/glass.svg
/usr/share/inkscape/examples/gradient-mesh-experimental.svgz
/usr/share/inkscape/examples/gradient.svg
/usr/share/inkscape/examples/i18n.svg
/usr/share/inkscape/examples/istest.pov
/usr/share/inkscape/examples/l-systems.svgz
/usr/share/inkscape/examples/lighting_filters.svg
/usr/share/inkscape/examples/live-path-effects-curvestitch.svg
/usr/share/inkscape/examples/live-path-effects-gears.svg
/usr/share/inkscape/examples/live-path-effects-pathalongpath.svg
/usr/share/inkscape/examples/markers.svg
/usr/share/inkscape/examples/replace-hue.svg
/usr/share/inkscape/examples/rope-3D.svg
/usr/share/inkscape/examples/stars.svgz
/usr/share/inkscape/examples/svgfont.svg
/usr/share/inkscape/examples/tesselation-P3.svg
/usr/share/inkscape/examples/text-on-path.svg
/usr/share/inkscape/examples/tiger.svgz
/usr/share/inkscape/examples/tref.svg
/usr/share/inkscape/examples/turbulence_filters.svg
/usr/share/inkscape/extensions/Barcode/Base.py
/usr/share/inkscape/extensions/Barcode/BaseEan.py
/usr/share/inkscape/extensions/Barcode/Code128.py
/usr/share/inkscape/extensions/Barcode/Code25i.py
/usr/share/inkscape/extensions/Barcode/Code39.py
/usr/share/inkscape/extensions/Barcode/Code39Ext.py
/usr/share/inkscape/extensions/Barcode/Code93.py
/usr/share/inkscape/extensions/Barcode/Ean13.py
/usr/share/inkscape/extensions/Barcode/Ean2.py
/usr/share/inkscape/extensions/Barcode/Ean5.py
/usr/share/inkscape/extensions/Barcode/Ean8.py
/usr/share/inkscape/extensions/Barcode/Rm4scc.py
/usr/share/inkscape/extensions/Barcode/Upca.py
/usr/share/inkscape/extensions/Barcode/Upce.py
/usr/share/inkscape/extensions/Barcode/__init__.py
/usr/share/inkscape/extensions/Poly3DObjects/cube.obj
/usr/share/inkscape/extensions/Poly3DObjects/cuboct.obj
/usr/share/inkscape/extensions/Poly3DObjects/dodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/great_dodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/great_rhombicosidodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/great_rhombicuboct.obj
/usr/share/inkscape/extensions/Poly3DObjects/great_stel_dodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/icos.obj
/usr/share/inkscape/extensions/Poly3DObjects/icosidodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/jessens_orthog_icos.obj
/usr/share/inkscape/extensions/Poly3DObjects/methane.obj
/usr/share/inkscape/extensions/Poly3DObjects/oct.obj
/usr/share/inkscape/extensions/Poly3DObjects/rh_axes.obj
/usr/share/inkscape/extensions/Poly3DObjects/rhomb_dodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/rhomb_triacont.obj
/usr/share/inkscape/extensions/Poly3DObjects/small_rhombicosidodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/small_rhombicuboct.obj
/usr/share/inkscape/extensions/Poly3DObjects/small_triam_icos.obj
/usr/share/inkscape/extensions/Poly3DObjects/snub_cube.obj
/usr/share/inkscape/extensions/Poly3DObjects/snub_dodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/szilassi.obj
/usr/share/inkscape/extensions/Poly3DObjects/tet.obj
/usr/share/inkscape/extensions/Poly3DObjects/trunc_cube.obj
/usr/share/inkscape/extensions/Poly3DObjects/trunc_dodec.obj
/usr/share/inkscape/extensions/Poly3DObjects/trunc_icos.obj
/usr/share/inkscape/extensions/Poly3DObjects/trunc_oct.obj
/usr/share/inkscape/extensions/Poly3DObjects/trunc_tet.obj
/usr/share/inkscape/extensions/addnodes.inx
/usr/share/inkscape/extensions/addnodes.py
/usr/share/inkscape/extensions/ai_input.inx
/usr/share/inkscape/extensions/aisvg.inx
/usr/share/inkscape/extensions/aisvg.xslt
/usr/share/inkscape/extensions/alphabet_soup/2.svg
/usr/share/inkscape/extensions/alphabet_soup/3.svg
/usr/share/inkscape/extensions/alphabet_soup/6.svg
/usr/share/inkscape/extensions/alphabet_soup/7.svg
/usr/share/inkscape/extensions/alphabet_soup/Cblob.svg
/usr/share/inkscape/extensions/alphabet_soup/Chook.svg
/usr/share/inkscape/extensions/alphabet_soup/Ctail.svg
/usr/share/inkscape/extensions/alphabet_soup/Delta.svg
/usr/share/inkscape/extensions/alphabet_soup/Eb.svg
/usr/share/inkscape/extensions/alphabet_soup/Eserif.svg
/usr/share/inkscape/extensions/alphabet_soup/Et.svg
/usr/share/inkscape/extensions/alphabet_soup/G.svg
/usr/share/inkscape/extensions/alphabet_soup/IBSerif.svg
/usr/share/inkscape/extensions/alphabet_soup/ITSerif.svg
/usr/share/inkscape/extensions/alphabet_soup/Lb.svg
/usr/share/inkscape/extensions/alphabet_soup/Lt.svg
/usr/share/inkscape/extensions/alphabet_soup/Ocross.svg
/usr/share/inkscape/extensions/alphabet_soup/Oterm.svg
/usr/share/inkscape/extensions/alphabet_soup/P.svg
/usr/share/inkscape/extensions/alphabet_soup/Q.svg
/usr/share/inkscape/extensions/alphabet_soup/Rblock.svg
/usr/share/inkscape/extensions/alphabet_soup/Tb.svg
/usr/share/inkscape/extensions/alphabet_soup/Tt.svg
/usr/share/inkscape/extensions/alphabet_soup/U.svg
/usr/share/inkscape/extensions/alphabet_soup/Vser.svg
/usr/share/inkscape/extensions/alphabet_soup/Xh.svg
/usr/share/inkscape/extensions/alphabet_soup/Xne.svg
/usr/share/inkscape/extensions/alphabet_soup/Xnw.svg
/usr/share/inkscape/extensions/alphabet_soup/Xvb.svg
/usr/share/inkscape/extensions/alphabet_soup/Xvt.svg
/usr/share/inkscape/extensions/alphabet_soup/a.svg
/usr/share/inkscape/extensions/alphabet_soup/abase.svg
/usr/share/inkscape/extensions/alphabet_soup/acap.svg
/usr/share/inkscape/extensions/alphabet_soup/b.svg
/usr/share/inkscape/extensions/alphabet_soup/bar.svg
/usr/share/inkscape/extensions/alphabet_soup/bar2.svg
/usr/share/inkscape/extensions/alphabet_soup/barcap.svg
/usr/share/inkscape/extensions/alphabet_soup/c.svg
/usr/share/inkscape/extensions/alphabet_soup/cross.svg
/usr/share/inkscape/extensions/alphabet_soup/cserif.svg
/usr/share/inkscape/extensions/alphabet_soup/e.svg
/usr/share/inkscape/extensions/alphabet_soup/epsilon.svg
/usr/share/inkscape/extensions/alphabet_soup/f.svg
/usr/share/inkscape/extensions/alphabet_soup/gamma.svg
/usr/share/inkscape/extensions/alphabet_soup/h.svg
/usr/share/inkscape/extensions/alphabet_soup/h2.svg
/usr/share/inkscape/extensions/alphabet_soup/hcap.svg
/usr/share/inkscape/extensions/alphabet_soup/idot.svg
/usr/share/inkscape/extensions/alphabet_soup/j.svg
/usr/share/inkscape/extensions/alphabet_soup/k.svg
/usr/share/inkscape/extensions/alphabet_soup/l.svg
/usr/share/inkscape/extensions/alphabet_soup/lserif.svg
/usr/share/inkscape/extensions/alphabet_soup/m.svg
/usr/share/inkscape/extensions/alphabet_soup/mcap.svg
/usr/share/inkscape/extensions/alphabet_soup/n.svg
/usr/share/inkscape/extensions/alphabet_soup/o.svg
/usr/share/inkscape/extensions/alphabet_soup/ocap.svg
/usr/share/inkscape/extensions/alphabet_soup/question.svg
/usr/share/inkscape/extensions/alphabet_soup/r.svg
/usr/share/inkscape/extensions/alphabet_soup/rcap.svg
/usr/share/inkscape/extensions/alphabet_soup/s.svg
/usr/share/inkscape/extensions/alphabet_soup/serif.svg
/usr/share/inkscape/extensions/alphabet_soup/t.svg
/usr/share/inkscape/extensions/alphabet_soup/tserif.svg
/usr/share/inkscape/extensions/alphabet_soup/v.svg
/usr/share/inkscape/extensions/alphabet_soup/vcap.svg
/usr/share/inkscape/extensions/alphabet_soup/vserl.svg
/usr/share/inkscape/extensions/alphabet_soup/vserr.svg
/usr/share/inkscape/extensions/alphabet_soup/x.svg
/usr/share/inkscape/extensions/alphabet_soup/y.svg
/usr/share/inkscape/extensions/alphabet_soup/yogh.svg
/usr/share/inkscape/extensions/alphabet_soup/z.svg
/usr/share/inkscape/extensions/bezmisc.py
/usr/share/inkscape/extensions/ccx_input.inx
/usr/share/inkscape/extensions/cdr_input.inx
/usr/share/inkscape/extensions/cdt_input.inx
/usr/share/inkscape/extensions/cgm_input.inx
/usr/share/inkscape/extensions/chardataeffect.py
/usr/share/inkscape/extensions/cmx_input.inx
/usr/share/inkscape/extensions/color_HSL_adjust.inx
/usr/share/inkscape/extensions/color_HSL_adjust.py
/usr/share/inkscape/extensions/color_blackandwhite.inx
/usr/share/inkscape/extensions/color_blackandwhite.py
/usr/share/inkscape/extensions/color_brighter.inx
/usr/share/inkscape/extensions/color_brighter.py
/usr/share/inkscape/extensions/color_custom.inx
/usr/share/inkscape/extensions/color_custom.py
/usr/share/inkscape/extensions/color_darker.inx
/usr/share/inkscape/extensions/color_darker.py
/usr/share/inkscape/extensions/color_desaturate.inx
/usr/share/inkscape/extensions/color_desaturate.py
/usr/share/inkscape/extensions/color_grayscale.inx
/usr/share/inkscape/extensions/color_grayscale.py
/usr/share/inkscape/extensions/color_lesshue.inx
/usr/share/inkscape/extensions/color_lesshue.py
/usr/share/inkscape/extensions/color_lesslight.inx
/usr/share/inkscape/extensions/color_lesslight.py
/usr/share/inkscape/extensions/color_lesssaturation.inx
/usr/share/inkscape/extensions/color_lesssaturation.py
/usr/share/inkscape/extensions/color_morehue.inx
/usr/share/inkscape/extensions/color_morehue.py
/usr/share/inkscape/extensions/color_morelight.inx
/usr/share/inkscape/extensions/color_morelight.py
/usr/share/inkscape/extensions/color_moresaturation.inx
/usr/share/inkscape/extensions/color_moresaturation.py
/usr/share/inkscape/extensions/color_negative.inx
/usr/share/inkscape/extensions/color_negative.py
/usr/share/inkscape/extensions/color_randomize.inx
/usr/share/inkscape/extensions/color_randomize.py
/usr/share/inkscape/extensions/color_removeblue.inx
/usr/share/inkscape/extensions/color_removeblue.py
/usr/share/inkscape/extensions/color_removegreen.inx
/usr/share/inkscape/extensions/color_removegreen.py
/usr/share/inkscape/extensions/color_removered.inx
/usr/share/inkscape/extensions/color_removered.py
/usr/share/inkscape/extensions/color_replace.inx
/usr/share/inkscape/extensions/color_replace.py
/usr/share/inkscape/extensions/color_rgbbarrel.inx
/usr/share/inkscape/extensions/color_rgbbarrel.py
/usr/share/inkscape/extensions/coloreffect.py
/usr/share/inkscape/extensions/colors.xml
/usr/share/inkscape/extensions/convert2dashes.inx
/usr/share/inkscape/extensions/convert2dashes.py
/usr/share/inkscape/extensions/cspsubdiv.py
/usr/share/inkscape/extensions/cubicsuperpath.py
/usr/share/inkscape/extensions/dhw_input.inx
/usr/share/inkscape/extensions/dia.inx
/usr/share/inkscape/extensions/dia2svg.sh
/usr/share/inkscape/extensions/dimension.inx
/usr/share/inkscape/extensions/dimension.py
/usr/share/inkscape/extensions/dm2svg.py
/usr/share/inkscape/extensions/docinfo.inx
/usr/share/inkscape/extensions/dots.inx
/usr/share/inkscape/extensions/dots.py
/usr/share/inkscape/extensions/dpi90to96.inx
/usr/share/inkscape/extensions/dpi96to90.inx
/usr/share/inkscape/extensions/dpiswitcher.py
/usr/share/inkscape/extensions/draw_from_triangle.inx
/usr/share/inkscape/extensions/draw_from_triangle.py
/usr/share/inkscape/extensions/dxf_input.inx
/usr/share/inkscape/extensions/dxf_input.py
/usr/share/inkscape/extensions/dxf_outlines.inx
/usr/share/inkscape/extensions/dxf_outlines.py
/usr/share/inkscape/extensions/dxf_output.inx
/usr/share/inkscape/extensions/dxf_templates.py
/usr/share/inkscape/extensions/edge3d.inx
/usr/share/inkscape/extensions/edge3d.py
/usr/share/inkscape/extensions/embed_raster_in_svg.pl
/usr/share/inkscape/extensions/embedimage.inx
/usr/share/inkscape/extensions/embedimage.py
/usr/share/inkscape/extensions/embedselectedimages.inx
/usr/share/inkscape/extensions/empty_business_card.inx
/usr/share/inkscape/extensions/empty_business_card.py
/usr/share/inkscape/extensions/empty_desktop.inx
/usr/share/inkscape/extensions/empty_desktop.py
/usr/share/inkscape/extensions/empty_dvd_cover.inx
/usr/share/inkscape/extensions/empty_dvd_cover.py
/usr/share/inkscape/extensions/empty_generic.inx
/usr/share/inkscape/extensions/empty_generic.py
/usr/share/inkscape/extensions/empty_icon.inx
/usr/share/inkscape/extensions/empty_icon.py
/usr/share/inkscape/extensions/empty_page.inx
/usr/share/inkscape/extensions/empty_page.py
/usr/share/inkscape/extensions/empty_video.inx
/usr/share/inkscape/extensions/empty_video.py
/usr/share/inkscape/extensions/eps_input.inx
/usr/share/inkscape/extensions/eqtexsvg.inx
/usr/share/inkscape/extensions/eqtexsvg.py
/usr/share/inkscape/extensions/export_gimp_palette.inx
/usr/share/inkscape/extensions/export_gimp_palette.py
/usr/share/inkscape/extensions/extractimage.inx
/usr/share/inkscape/extensions/extractimage.py
/usr/share/inkscape/extensions/extrude.inx
/usr/share/inkscape/extensions/extrude.py
/usr/share/inkscape/extensions/ffgeom.py
/usr/share/inkscape/extensions/fig2dev-ext.py
/usr/share/inkscape/extensions/fig_input.inx
/usr/share/inkscape/extensions/flatten.inx
/usr/share/inkscape/extensions/flatten.py
/usr/share/inkscape/extensions/foldablebox.inx
/usr/share/inkscape/extensions/foldablebox.py
/usr/share/inkscape/extensions/fontfix.conf
/usr/share/inkscape/extensions/fractalize.inx
/usr/share/inkscape/extensions/fractalize.py
/usr/share/inkscape/extensions/funcplot.inx
/usr/share/inkscape/extensions/funcplot.py
/usr/share/inkscape/extensions/gcodetools.py
/usr/share/inkscape/extensions/gcodetools_about.inx
/usr/share/inkscape/extensions/gcodetools_area.inx
/usr/share/inkscape/extensions/gcodetools_check_for_updates.inx
/usr/share/inkscape/extensions/gcodetools_dxf_points.inx
/usr/share/inkscape/extensions/gcodetools_engraving.inx
/usr/share/inkscape/extensions/gcodetools_graffiti.inx
/usr/share/inkscape/extensions/gcodetools_lathe.inx
/usr/share/inkscape/extensions/gcodetools_orientation_points.inx
/usr/share/inkscape/extensions/gcodetools_path_to_gcode.inx
/usr/share/inkscape/extensions/gcodetools_prepare_path_for_plasma.inx
/usr/share/inkscape/extensions/gcodetools_tools_library.inx
/usr/share/inkscape/extensions/generate_voronoi.inx
/usr/share/inkscape/extensions/generate_voronoi.py
/usr/share/inkscape/extensions/genpofiles.sh
/usr/share/inkscape/extensions/gimp_xcf.inx
/usr/share/inkscape/extensions/gimp_xcf.py
/usr/share/inkscape/extensions/grid_cartesian.inx
/usr/share/inkscape/extensions/grid_cartesian.py
/usr/share/inkscape/extensions/grid_isometric.inx
/usr/share/inkscape/extensions/grid_isometric.py
/usr/share/inkscape/extensions/grid_polar.inx
/usr/share/inkscape/extensions/grid_polar.py
/usr/share/inkscape/extensions/guides_creator.inx
/usr/share/inkscape/extensions/guides_creator.py
/usr/share/inkscape/extensions/guillotine.inx
/usr/share/inkscape/extensions/guillotine.py
/usr/share/inkscape/extensions/handles.inx
/usr/share/inkscape/extensions/handles.py
/usr/share/inkscape/extensions/hershey.inx
/usr/share/inkscape/extensions/hershey.py
/usr/share/inkscape/extensions/hersheydata.py
/usr/share/inkscape/extensions/hpgl_decoder.py
/usr/share/inkscape/extensions/hpgl_encoder.py
/usr/share/inkscape/extensions/hpgl_input.inx
/usr/share/inkscape/extensions/hpgl_input.py
/usr/share/inkscape/extensions/hpgl_output.inx
/usr/share/inkscape/extensions/hpgl_output.py
/usr/share/inkscape/extensions/image_attributes.inx
/usr/share/inkscape/extensions/image_attributes.py
/usr/share/inkscape/extensions/ink2canvas.inx
/usr/share/inkscape/extensions/ink2canvas.py
/usr/share/inkscape/extensions/ink2canvas/__init__.py
/usr/share/inkscape/extensions/ink2canvas/canvas.py
/usr/share/inkscape/extensions/ink2canvas/svg.py
/usr/share/inkscape/extensions/inkex.py
/usr/share/inkscape/extensions/inkscape.extension.rng
/usr/share/inkscape/extensions/inkscape_follow_link.inx
/usr/share/inkscape/extensions/inkscape_follow_link.py
/usr/share/inkscape/extensions/inkscape_help_askaquestion.inx
/usr/share/inkscape/extensions/inkscape_help_commandline.inx
/usr/share/inkscape/extensions/inkscape_help_faq.inx
/usr/share/inkscape/extensions/inkscape_help_keys.inx
/usr/share/inkscape/extensions/inkscape_help_manual.inx
/usr/share/inkscape/extensions/inkscape_help_relnotes.inx
/usr/share/inkscape/extensions/inkscape_help_reportabug.inx
/usr/share/inkscape/extensions/inkscape_help_svgspec.inx
/usr/share/inkscape/extensions/inkweb.js
/usr/share/inkscape/extensions/inkwebeffect.py
/usr/share/inkscape/extensions/interp.inx
/usr/share/inkscape/extensions/interp.py
/usr/share/inkscape/extensions/interp_att_g.inx
/usr/share/inkscape/extensions/interp_att_g.py
/usr/share/inkscape/extensions/jessyInk.js
/usr/share/inkscape/extensions/jessyInk_autoTexts.inx
/usr/share/inkscape/extensions/jessyInk_autoTexts.py
/usr/share/inkscape/extensions/jessyInk_core_mouseHandler_noclick.js
/usr/share/inkscape/extensions/jessyInk_core_mouseHandler_zoomControl.js
/usr/share/inkscape/extensions/jessyInk_effects.inx
/usr/share/inkscape/extensions/jessyInk_effects.py
/usr/share/inkscape/extensions/jessyInk_export.inx
/usr/share/inkscape/extensions/jessyInk_export.py
/usr/share/inkscape/extensions/jessyInk_install.inx
/usr/share/inkscape/extensions/jessyInk_install.py
/usr/share/inkscape/extensions/jessyInk_keyBindings.inx
/usr/share/inkscape/extensions/jessyInk_keyBindings.py
/usr/share/inkscape/extensions/jessyInk_masterSlide.inx
/usr/share/inkscape/extensions/jessyInk_masterSlide.py
/usr/share/inkscape/extensions/jessyInk_mouseHandler.inx
/usr/share/inkscape/extensions/jessyInk_mouseHandler.py
/usr/share/inkscape/extensions/jessyInk_summary.inx
/usr/share/inkscape/extensions/jessyInk_summary.py
/usr/share/inkscape/extensions/jessyInk_transitions.inx
/usr/share/inkscape/extensions/jessyInk_transitions.py
/usr/share/inkscape/extensions/jessyInk_uninstall.inx
/usr/share/inkscape/extensions/jessyInk_uninstall.py
/usr/share/inkscape/extensions/jessyInk_video.inx
/usr/share/inkscape/extensions/jessyInk_video.py
/usr/share/inkscape/extensions/jessyInk_video.svg
/usr/share/inkscape/extensions/jessyInk_view.inx
/usr/share/inkscape/extensions/jessyInk_view.py
/usr/share/inkscape/extensions/jitternodes.inx
/usr/share/inkscape/extensions/jitternodes.py
/usr/share/inkscape/extensions/launch_webbrowser.py
/usr/share/inkscape/extensions/layers2svgfont.inx
/usr/share/inkscape/extensions/layers2svgfont.py
/usr/share/inkscape/extensions/layout_nup.inx
/usr/share/inkscape/extensions/layout_nup.py
/usr/share/inkscape/extensions/lindenmayer.inx
/usr/share/inkscape/extensions/lindenmayer.py
/usr/share/inkscape/extensions/lorem_ipsum.inx
/usr/share/inkscape/extensions/lorem_ipsum.py
/usr/share/inkscape/extensions/markers_strokepaint.inx
/usr/share/inkscape/extensions/markers_strokepaint.py
/usr/share/inkscape/extensions/measure.inx
/usr/share/inkscape/extensions/measure.py
/usr/share/inkscape/extensions/merge_styles.inx
/usr/share/inkscape/extensions/merge_styles.py
/usr/share/inkscape/extensions/motion.inx
/usr/share/inkscape/extensions/motion.py
/usr/share/inkscape/extensions/new_glyph_layer.inx
/usr/share/inkscape/extensions/new_glyph_layer.py
/usr/share/inkscape/extensions/next_glyph_layer.inx
/usr/share/inkscape/extensions/next_glyph_layer.py
/usr/share/inkscape/extensions/nicechart.inx
/usr/share/inkscape/extensions/nicechart.py
/usr/share/inkscape/extensions/param_curves.inx
/usr/share/inkscape/extensions/param_curves.py
/usr/share/inkscape/extensions/pathalongpath.inx
/usr/share/inkscape/extensions/pathalongpath.py
/usr/share/inkscape/extensions/pathmodifier.py
/usr/share/inkscape/extensions/pathscatter.inx
/usr/share/inkscape/extensions/pathscatter.py
/usr/share/inkscape/extensions/perfectboundcover.inx
/usr/share/inkscape/extensions/perfectboundcover.py
/usr/share/inkscape/extensions/perspective.inx
/usr/share/inkscape/extensions/perspective.py
/usr/share/inkscape/extensions/pixelsnap.inx
/usr/share/inkscape/extensions/pixelsnap.py
/usr/share/inkscape/extensions/plotter.inx
/usr/share/inkscape/extensions/plotter.py
/usr/share/inkscape/extensions/plt_input.inx
/usr/share/inkscape/extensions/plt_output.inx
/usr/share/inkscape/extensions/plt_output.py
/usr/share/inkscape/extensions/polyhedron_3d.inx
/usr/share/inkscape/extensions/polyhedron_3d.py
/usr/share/inkscape/extensions/previous_glyph_layer.inx
/usr/share/inkscape/extensions/previous_glyph_layer.py
/usr/share/inkscape/extensions/print_win32_vector.inx
/usr/share/inkscape/extensions/print_win32_vector.py
/usr/share/inkscape/extensions/printing_marks.inx
/usr/share/inkscape/extensions/printing_marks.py
/usr/share/inkscape/extensions/ps2dxf.sh
/usr/share/inkscape/extensions/ps2pdf-ext.py
/usr/share/inkscape/extensions/ps_input.inx
/usr/share/inkscape/extensions/pturtle.py
/usr/share/inkscape/extensions/render_alphabetsoup.inx
/usr/share/inkscape/extensions/render_alphabetsoup.py
/usr/share/inkscape/extensions/render_alphabetsoup_config.py
/usr/share/inkscape/extensions/render_barcode.inx
/usr/share/inkscape/extensions/render_barcode.py
/usr/share/inkscape/extensions/render_barcode_datamatrix.inx
/usr/share/inkscape/extensions/render_barcode_datamatrix.py
/usr/share/inkscape/extensions/render_barcode_qrcode.inx
/usr/share/inkscape/extensions/render_barcode_qrcode.py
/usr/share/inkscape/extensions/render_gear_rack.inx
/usr/share/inkscape/extensions/render_gear_rack.py
/usr/share/inkscape/extensions/render_gears.inx
/usr/share/inkscape/extensions/render_gears.py
/usr/share/inkscape/extensions/replace_font.inx
/usr/share/inkscape/extensions/replace_font.py
/usr/share/inkscape/extensions/restack.inx
/usr/share/inkscape/extensions/restack.py
/usr/share/inkscape/extensions/rtree.inx
/usr/share/inkscape/extensions/rtree.py
/usr/share/inkscape/extensions/rubberstretch.inx
/usr/share/inkscape/extensions/rubberstretch.py
/usr/share/inkscape/extensions/run_command.py
/usr/share/inkscape/extensions/scour.inkscape.py
/usr/share/inkscape/extensions/scour.inx
/usr/share/inkscape/extensions/seamless_pattern.inx
/usr/share/inkscape/extensions/seamless_pattern.py
/usr/share/inkscape/extensions/seamless_pattern.svg
/usr/share/inkscape/extensions/seamless_pattern_procedural.inx
/usr/share/inkscape/extensions/setup_typography_canvas.inx
/usr/share/inkscape/extensions/setup_typography_canvas.py
/usr/share/inkscape/extensions/simplepath.py
/usr/share/inkscape/extensions/simplepath.rb
/usr/share/inkscape/extensions/simplestyle.py
/usr/share/inkscape/extensions/simpletransform.py
/usr/share/inkscape/extensions/sk1_input.inx
/usr/share/inkscape/extensions/sk1_output.inx
/usr/share/inkscape/extensions/sk1_output.py
/usr/share/inkscape/extensions/sk2svg.sh
/usr/share/inkscape/extensions/sk_input.inx
/usr/share/inkscape/extensions/spirograph.inx
/usr/share/inkscape/extensions/spirograph.py
/usr/share/inkscape/extensions/split.inx
/usr/share/inkscape/extensions/split.py
/usr/share/inkscape/extensions/straightseg.inx
/usr/share/inkscape/extensions/straightseg.py
/usr/share/inkscape/extensions/summersnight.inx
/usr/share/inkscape/extensions/summersnight.py
/usr/share/inkscape/extensions/svg2fxg.inx
/usr/share/inkscape/extensions/svg2fxg.xsl
/usr/share/inkscape/extensions/svg2xaml.inx
/usr/share/inkscape/extensions/svg2xaml.xsl
/usr/share/inkscape/extensions/svg_and_media_zip_output.inx
/usr/share/inkscape/extensions/svg_and_media_zip_output.py
/usr/share/inkscape/extensions/svgcalendar.inx
/usr/share/inkscape/extensions/svgcalendar.py
/usr/share/inkscape/extensions/svgfont2layers.inx
/usr/share/inkscape/extensions/svgfont2layers.py
/usr/share/inkscape/extensions/synfig_fileformat.py
/usr/share/inkscape/extensions/synfig_output.inx
/usr/share/inkscape/extensions/synfig_output.py
/usr/share/inkscape/extensions/synfig_prepare.py
/usr/share/inkscape/extensions/tar_layers.inx
/usr/share/inkscape/extensions/tar_layers.py
/usr/share/inkscape/extensions/test/svg/default-inkscape-SVG.svg
/usr/share/inkscape/extensions/test/svg/default-plain-SVG.svg
/usr/share/inkscape/extensions/test/svg/empty-SVG.svg
/usr/share/inkscape/extensions/test/svg/multilayered-test.svg
/usr/share/inkscape/extensions/text_braille.inx
/usr/share/inkscape/extensions/text_braille.py
/usr/share/inkscape/extensions/text_extract.inx
/usr/share/inkscape/extensions/text_extract.py
/usr/share/inkscape/extensions/text_flipcase.inx
/usr/share/inkscape/extensions/text_flipcase.py
/usr/share/inkscape/extensions/text_lowercase.inx
/usr/share/inkscape/extensions/text_lowercase.py
/usr/share/inkscape/extensions/text_merge.inx
/usr/share/inkscape/extensions/text_merge.py
/usr/share/inkscape/extensions/text_randomcase.inx
/usr/share/inkscape/extensions/text_randomcase.py
/usr/share/inkscape/extensions/text_sentencecase.inx
/usr/share/inkscape/extensions/text_sentencecase.py
/usr/share/inkscape/extensions/text_titlecase.inx
/usr/share/inkscape/extensions/text_titlecase.py
/usr/share/inkscape/extensions/text_uppercase.inx
/usr/share/inkscape/extensions/text_uppercase.py
/usr/share/inkscape/extensions/triangle.inx
/usr/share/inkscape/extensions/triangle.py
/usr/share/inkscape/extensions/ungroup_deep.inx
/usr/share/inkscape/extensions/ungroup_deep.py
/usr/share/inkscape/extensions/uniconv-ext.py
/usr/share/inkscape/extensions/uniconv_output.py
/usr/share/inkscape/extensions/voronoi.py
/usr/share/inkscape/extensions/voronoi2svg.inx
/usr/share/inkscape/extensions/voronoi2svg.py
/usr/share/inkscape/extensions/web-set-att.inx
/usr/share/inkscape/extensions/web-set-att.py
/usr/share/inkscape/extensions/web-transmit-att.inx
/usr/share/inkscape/extensions/web-transmit-att.py
/usr/share/inkscape/extensions/webslicer_create_group.inx
/usr/share/inkscape/extensions/webslicer_create_group.py
/usr/share/inkscape/extensions/webslicer_create_rect.inx
/usr/share/inkscape/extensions/webslicer_create_rect.py
/usr/share/inkscape/extensions/webslicer_effect.py
/usr/share/inkscape/extensions/webslicer_export.inx
/usr/share/inkscape/extensions/webslicer_export.py
/usr/share/inkscape/extensions/whirl.inx
/usr/share/inkscape/extensions/whirl.py
/usr/share/inkscape/extensions/wireframe_sphere.inx
/usr/share/inkscape/extensions/wireframe_sphere.py
/usr/share/inkscape/extensions/wmf_input.inx
/usr/share/inkscape/extensions/wmf_output.inx
/usr/share/inkscape/extensions/wmf_output.py
/usr/share/inkscape/extensions/xaml2svg.inx
/usr/share/inkscape/extensions/xaml2svg.xsl
/usr/share/inkscape/extensions/xaml2svg/Makefile.am
/usr/share/inkscape/extensions/xaml2svg/animation.xsl
/usr/share/inkscape/extensions/xaml2svg/brushes.xsl
/usr/share/inkscape/extensions/xaml2svg/canvas.xsl
/usr/share/inkscape/extensions/xaml2svg/geometry.xsl
/usr/share/inkscape/extensions/xaml2svg/properties.xsl
/usr/share/inkscape/extensions/xaml2svg/shapes.xsl
/usr/share/inkscape/extensions/xaml2svg/transform.xsl
/usr/share/inkscape/filters/README
/usr/share/inkscape/filters/filters.svg
/usr/share/inkscape/filters/filters.svg.h
/usr/share/inkscape/fonts/README
/usr/share/inkscape/gradients/README
/usr/share/inkscape/icons/OCAL.png
/usr/share/inkscape/icons/README
/usr/share/inkscape/icons/color-management-icon.png
/usr/share/inkscape/icons/feBlend-icon.png
/usr/share/inkscape/icons/feBlend-icon.svg
/usr/share/inkscape/icons/feColorMatrix-icon.png
/usr/share/inkscape/icons/feColorMatrix-icon.svg
/usr/share/inkscape/icons/feComposite-icon.png
/usr/share/inkscape/icons/feComposite-icon.svg
/usr/share/inkscape/icons/feConvolveMatrix-icon.png
/usr/share/inkscape/icons/feConvolveMatrix-icon.svg
/usr/share/inkscape/icons/feDiffuseLighting-icon.png
/usr/share/inkscape/icons/feDiffuseLighting-icon.svg
/usr/share/inkscape/icons/feDisplacementMap-icon.png
/usr/share/inkscape/icons/feDisplacementMap-icon.svg
/usr/share/inkscape/icons/feFlood-icon.png
/usr/share/inkscape/icons/feFlood-icon.svg
/usr/share/inkscape/icons/feGaussianBlur-icon.png
/usr/share/inkscape/icons/feGaussianBlur-icon.svg
/usr/share/inkscape/icons/feImage-icon.png
/usr/share/inkscape/icons/feImage-icon.svg
/usr/share/inkscape/icons/feMerge-icon.png
/usr/share/inkscape/icons/feMerge-icon.svg
/usr/share/inkscape/icons/feMorphology-icon.png
/usr/share/inkscape/icons/feMorphology-icon.svg
/usr/share/inkscape/icons/feOffset-icon.png
/usr/share/inkscape/icons/feOffset-icon.svg
/usr/share/inkscape/icons/feSpecularLighting-icon.png
/usr/share/inkscape/icons/feSpecularLighting-icon.svg
/usr/share/inkscape/icons/feTurbulence-icon.png
/usr/share/inkscape/icons/feTurbulence-icon.svg
/usr/share/inkscape/icons/icons.svg
/usr/share/inkscape/icons/inkscape.file.png
/usr/share/inkscape/icons/inkscape.file.svg
/usr/share/inkscape/icons/inkscape.svg
/usr/share/inkscape/icons/out-of-gamut-icon.png
/usr/share/inkscape/icons/out-of-gamut-icon.svg
/usr/share/inkscape/icons/remove-color.png
/usr/share/inkscape/icons/remove-color.svg
/usr/share/inkscape/icons/symbolic_icons.svg
/usr/share/inkscape/icons/tango_icons.svg
/usr/share/inkscape/icons/ticotico.jpg
/usr/share/inkscape/icons/too-much-ink-icon.png
/usr/share/inkscape/icons/too-much-ink-icon.svg
/usr/share/inkscape/keys/acd-canvas.xml
/usr/share/inkscape/keys/adobe-illustrator-cs2.xml
/usr/share/inkscape/keys/corel-draw-x4.xml
/usr/share/inkscape/keys/corel-draw-x8.xml
/usr/share/inkscape/keys/default.xml
/usr/share/inkscape/keys/inkscape.xml
/usr/share/inkscape/keys/macromedia-freehand-mx.xml
/usr/share/inkscape/keys/right-handed-illustration.xml
/usr/share/inkscape/keys/xara.xml
/usr/share/inkscape/keys/zoner-draw.xml
/usr/share/inkscape/markers/markers.svg
/usr/share/inkscape/palettes/Android-icon-palette.gpl
/usr/share/inkscape/palettes/Blues.gpl
/usr/share/inkscape/palettes/Gold.gpl
/usr/share/inkscape/palettes/Gray.gpl
/usr/share/inkscape/palettes/Greens.gpl
/usr/share/inkscape/palettes/Hilite.gpl
/usr/share/inkscape/palettes/Khaki.gpl
/usr/share/inkscape/palettes/LaTeX-Beamer.gpl
/usr/share/inkscape/palettes/MATLAB-Jet-72.gpl
/usr/share/inkscape/palettes/README
/usr/share/inkscape/palettes/Reds.gpl
/usr/share/inkscape/palettes/Royal.gpl
/usr/share/inkscape/palettes/Tango-Palette.gpl
/usr/share/inkscape/palettes/Topographic.gpl
/usr/share/inkscape/palettes/Ubuntu.gpl
/usr/share/inkscape/palettes/echo-palette.gpl
/usr/share/inkscape/palettes/inkscape.gpl
/usr/share/inkscape/palettes/palettes.h
/usr/share/inkscape/palettes/svg.gpl
/usr/share/inkscape/palettes/webhex.gpl
/usr/share/inkscape/palettes/websafe22.gpl
/usr/share/inkscape/palettes/windowsXP.gpl
/usr/share/inkscape/patterns/README
/usr/share/inkscape/patterns/patterns.svg
/usr/share/inkscape/patterns/patterns.svg.h
/usr/share/inkscape/screens/about.svg
/usr/share/inkscape/symbols/AigaSymbols.svg
/usr/share/inkscape/symbols/BalloonSymbols.svg
/usr/share/inkscape/symbols/FlowSymbols.svg
/usr/share/inkscape/symbols/LogicSymbols.svg
/usr/share/inkscape/symbols/MapSymbolsNPS.svg
/usr/share/inkscape/symbols/README
/usr/share/inkscape/symbols/symbols.h
/usr/share/inkscape/templates/CD_label_120x120.svg
/usr/share/inkscape/templates/LaTeX_Beamer.svg
/usr/share/inkscape/templates/README
/usr/share/inkscape/templates/Typography_Canvas.svg
/usr/share/inkscape/templates/default.be.svg
/usr/share/inkscape/templates/default.ca.svg
/usr/share/inkscape/templates/default.cs.svg
/usr/share/inkscape/templates/default.de.svg
/usr/share/inkscape/templates/default.en_US.svg
/usr/share/inkscape/templates/default.eo.svg
/usr/share/inkscape/templates/default.es.svg
/usr/share/inkscape/templates/default.eu.svg
/usr/share/inkscape/templates/default.fi.svg
/usr/share/inkscape/templates/default.fr.svg
/usr/share/inkscape/templates/default.hu.svg
/usr/share/inkscape/templates/default.is.svg
/usr/share/inkscape/templates/default.it.svg
/usr/share/inkscape/templates/default.ja.svg
/usr/share/inkscape/templates/default.lt.svg
/usr/share/inkscape/templates/default.nl.svg
/usr/share/inkscape/templates/default.pl.svg
/usr/share/inkscape/templates/default.pt_BR.svg
/usr/share/inkscape/templates/default.sk.svg
/usr/share/inkscape/templates/default.svg
/usr/share/inkscape/templates/default_pt.svg
/usr/share/inkscape/templates/default_px.svg
/usr/share/inkscape/templates/no_layers.svg
/usr/share/inkscape/templates/templates.h
/usr/share/inkscape/tutorials/README
/usr/share/inkscape/tutorials/edge3d.svg
/usr/share/inkscape/tutorials/gpl-2.svg
/usr/share/inkscape/tutorials/making_markers.svg
/usr/share/inkscape/tutorials/oldguitar.jpg
/usr/share/inkscape/tutorials/pixelart-dialog.de.png
/usr/share/inkscape/tutorials/pixelart-dialog.el.png
/usr/share/inkscape/tutorials/pixelart-dialog.en.png
/usr/share/inkscape/tutorials/pixelart-dialog.fr.png
/usr/share/inkscape/tutorials/pixelart-dialog.nl.png
/usr/share/inkscape/tutorials/pixelart-dialog.png
/usr/share/inkscape/tutorials/pixelart-dialog.pt.png
/usr/share/inkscape/tutorials/pixelart-dialog.ru.png
/usr/share/inkscape/tutorials/pixelart-dialog.sk.png
/usr/share/inkscape/tutorials/pixelart-dialog.zh_TW.png
/usr/share/inkscape/tutorials/potrace.de.png
/usr/share/inkscape/tutorials/potrace.el.png
/usr/share/inkscape/tutorials/potrace.en.png
/usr/share/inkscape/tutorials/potrace.es.png
/usr/share/inkscape/tutorials/potrace.eu.png
/usr/share/inkscape/tutorials/potrace.fr.png
/usr/share/inkscape/tutorials/potrace.gl.png
/usr/share/inkscape/tutorials/potrace.hu.png
/usr/share/inkscape/tutorials/potrace.id.png
/usr/share/inkscape/tutorials/potrace.ja.png
/usr/share/inkscape/tutorials/potrace.nl.png
/usr/share/inkscape/tutorials/potrace.pl.png
/usr/share/inkscape/tutorials/potrace.png
/usr/share/inkscape/tutorials/potrace.pt.png
/usr/share/inkscape/tutorials/potrace.pt_BR.png
/usr/share/inkscape/tutorials/potrace.ru.png
/usr/share/inkscape/tutorials/potrace.sk.png
/usr/share/inkscape/tutorials/potrace.sl.png
/usr/share/inkscape/tutorials/potrace.vi.png
/usr/share/inkscape/tutorials/potrace.zh_TW.png
/usr/share/inkscape/tutorials/tutorial-advanced.be.svg
/usr/share/inkscape/tutorials/tutorial-advanced.ca.svg
/usr/share/inkscape/tutorials/tutorial-advanced.cs.svg
/usr/share/inkscape/tutorials/tutorial-advanced.de.svg
/usr/share/inkscape/tutorials/tutorial-advanced.el.svg
/usr/share/inkscape/tutorials/tutorial-advanced.es.svg
/usr/share/inkscape/tutorials/tutorial-advanced.eu.svg
/usr/share/inkscape/tutorials/tutorial-advanced.fa.svg
/usr/share/inkscape/tutorials/tutorial-advanced.fr.svg
/usr/share/inkscape/tutorials/tutorial-advanced.gl.svg
/usr/share/inkscape/tutorials/tutorial-advanced.hu.svg
/usr/share/inkscape/tutorials/tutorial-advanced.id.svg
/usr/share/inkscape/tutorials/tutorial-advanced.it.svg
/usr/share/inkscape/tutorials/tutorial-advanced.ja.svg
/usr/share/inkscape/tutorials/tutorial-advanced.nl.svg
/usr/share/inkscape/tutorials/tutorial-advanced.pl.svg
/usr/share/inkscape/tutorials/tutorial-advanced.pt.svg
/usr/share/inkscape/tutorials/tutorial-advanced.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-advanced.ru.svg
/usr/share/inkscape/tutorials/tutorial-advanced.sk.svg
/usr/share/inkscape/tutorials/tutorial-advanced.sl.svg
/usr/share/inkscape/tutorials/tutorial-advanced.svg
/usr/share/inkscape/tutorials/tutorial-advanced.vi.svg
/usr/share/inkscape/tutorials/tutorial-advanced.zh_CN.svg
/usr/share/inkscape/tutorials/tutorial-advanced.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-basic.be.svg
/usr/share/inkscape/tutorials/tutorial-basic.bg.svg
/usr/share/inkscape/tutorials/tutorial-basic.ca.svg
/usr/share/inkscape/tutorials/tutorial-basic.cs.svg
/usr/share/inkscape/tutorials/tutorial-basic.da.svg
/usr/share/inkscape/tutorials/tutorial-basic.de.svg
/usr/share/inkscape/tutorials/tutorial-basic.el.svg
/usr/share/inkscape/tutorials/tutorial-basic.eo.svg
/usr/share/inkscape/tutorials/tutorial-basic.es.svg
/usr/share/inkscape/tutorials/tutorial-basic.eu.svg
/usr/share/inkscape/tutorials/tutorial-basic.fa.svg
/usr/share/inkscape/tutorials/tutorial-basic.fr.svg
/usr/share/inkscape/tutorials/tutorial-basic.gl.svg
/usr/share/inkscape/tutorials/tutorial-basic.hu.svg
/usr/share/inkscape/tutorials/tutorial-basic.id.svg
/usr/share/inkscape/tutorials/tutorial-basic.it.svg
/usr/share/inkscape/tutorials/tutorial-basic.ja.svg
/usr/share/inkscape/tutorials/tutorial-basic.nl.svg
/usr/share/inkscape/tutorials/tutorial-basic.nn.svg
/usr/share/inkscape/tutorials/tutorial-basic.pl.svg
/usr/share/inkscape/tutorials/tutorial-basic.pt.svg
/usr/share/inkscape/tutorials/tutorial-basic.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-basic.ru.svg
/usr/share/inkscape/tutorials/tutorial-basic.sk.svg
/usr/share/inkscape/tutorials/tutorial-basic.sl.svg
/usr/share/inkscape/tutorials/tutorial-basic.svg
/usr/share/inkscape/tutorials/tutorial-basic.tr.svg
/usr/share/inkscape/tutorials/tutorial-basic.vi.svg
/usr/share/inkscape/tutorials/tutorial-basic.zh_CN.svg
/usr/share/inkscape/tutorials/tutorial-basic.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.be.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.ca.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.cs.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.de.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.el.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.es.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.eu.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.fa.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.fr.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.gl.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.hu.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.id.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.ja.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.nl.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.pl.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.pt.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.ru.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.sk.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.sl.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.vi.svg
/usr/share/inkscape/tutorials/tutorial-calligraphy.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-elements.be.svg
/usr/share/inkscape/tutorials/tutorial-elements.ca.svg
/usr/share/inkscape/tutorials/tutorial-elements.de.svg
/usr/share/inkscape/tutorials/tutorial-elements.el.svg
/usr/share/inkscape/tutorials/tutorial-elements.es.svg
/usr/share/inkscape/tutorials/tutorial-elements.eu.svg
/usr/share/inkscape/tutorials/tutorial-elements.fa.svg
/usr/share/inkscape/tutorials/tutorial-elements.fr.svg
/usr/share/inkscape/tutorials/tutorial-elements.gl.svg
/usr/share/inkscape/tutorials/tutorial-elements.hu.svg
/usr/share/inkscape/tutorials/tutorial-elements.id.svg
/usr/share/inkscape/tutorials/tutorial-elements.it.svg
/usr/share/inkscape/tutorials/tutorial-elements.ja.svg
/usr/share/inkscape/tutorials/tutorial-elements.nl.svg
/usr/share/inkscape/tutorials/tutorial-elements.pl.svg
/usr/share/inkscape/tutorials/tutorial-elements.pt.svg
/usr/share/inkscape/tutorials/tutorial-elements.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-elements.ru.svg
/usr/share/inkscape/tutorials/tutorial-elements.sk.svg
/usr/share/inkscape/tutorials/tutorial-elements.sl.svg
/usr/share/inkscape/tutorials/tutorial-elements.svg
/usr/share/inkscape/tutorials/tutorial-elements.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.be.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.de.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.el.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.fr.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.gl.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.hu.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.ja.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.nl.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.pl.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.pt.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.ru.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.sk.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.sl.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.vi.svg
/usr/share/inkscape/tutorials/tutorial-interpolate.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-shapes.be.svg
/usr/share/inkscape/tutorials/tutorial-shapes.ca.svg
/usr/share/inkscape/tutorials/tutorial-shapes.cs.svg
/usr/share/inkscape/tutorials/tutorial-shapes.de.svg
/usr/share/inkscape/tutorials/tutorial-shapes.el.svg
/usr/share/inkscape/tutorials/tutorial-shapes.es.svg
/usr/share/inkscape/tutorials/tutorial-shapes.eu.svg
/usr/share/inkscape/tutorials/tutorial-shapes.fa.svg
/usr/share/inkscape/tutorials/tutorial-shapes.fr.svg
/usr/share/inkscape/tutorials/tutorial-shapes.gl.svg
/usr/share/inkscape/tutorials/tutorial-shapes.hu.svg
/usr/share/inkscape/tutorials/tutorial-shapes.id.svg
/usr/share/inkscape/tutorials/tutorial-shapes.it.svg
/usr/share/inkscape/tutorials/tutorial-shapes.ja.svg
/usr/share/inkscape/tutorials/tutorial-shapes.nl.svg
/usr/share/inkscape/tutorials/tutorial-shapes.pl.svg
/usr/share/inkscape/tutorials/tutorial-shapes.pt.svg
/usr/share/inkscape/tutorials/tutorial-shapes.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-shapes.ru.svg
/usr/share/inkscape/tutorials/tutorial-shapes.sk.svg
/usr/share/inkscape/tutorials/tutorial-shapes.sl.svg
/usr/share/inkscape/tutorials/tutorial-shapes.svg
/usr/share/inkscape/tutorials/tutorial-shapes.vi.svg
/usr/share/inkscape/tutorials/tutorial-shapes.zh_CN.svg
/usr/share/inkscape/tutorials/tutorial-shapes.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-tips.be.svg
/usr/share/inkscape/tutorials/tutorial-tips.ca.svg
/usr/share/inkscape/tutorials/tutorial-tips.de.svg
/usr/share/inkscape/tutorials/tutorial-tips.el.svg
/usr/share/inkscape/tutorials/tutorial-tips.es.svg
/usr/share/inkscape/tutorials/tutorial-tips.eu.svg
/usr/share/inkscape/tutorials/tutorial-tips.fa.svg
/usr/share/inkscape/tutorials/tutorial-tips.fr.svg
/usr/share/inkscape/tutorials/tutorial-tips.gl.svg
/usr/share/inkscape/tutorials/tutorial-tips.hu.svg
/usr/share/inkscape/tutorials/tutorial-tips.id.svg
/usr/share/inkscape/tutorials/tutorial-tips.it.svg
/usr/share/inkscape/tutorials/tutorial-tips.ja.svg
/usr/share/inkscape/tutorials/tutorial-tips.nl.svg
/usr/share/inkscape/tutorials/tutorial-tips.pl.svg
/usr/share/inkscape/tutorials/tutorial-tips.pt.svg
/usr/share/inkscape/tutorials/tutorial-tips.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-tips.ru.svg
/usr/share/inkscape/tutorials/tutorial-tips.sk.svg
/usr/share/inkscape/tutorials/tutorial-tips.sl.svg
/usr/share/inkscape/tutorials/tutorial-tips.svg
/usr/share/inkscape/tutorials/tutorial-tips.vi.svg
/usr/share/inkscape/tutorials/tutorial-tips.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.el.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.fr.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.nl.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.pt.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.ru.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.sk.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.svg
/usr/share/inkscape/tutorials/tutorial-tracing-pixelart.zh_TW.svg
/usr/share/inkscape/tutorials/tutorial-tracing.be.svg
/usr/share/inkscape/tutorials/tutorial-tracing.ca.svg
/usr/share/inkscape/tutorials/tutorial-tracing.de.svg
/usr/share/inkscape/tutorials/tutorial-tracing.el.svg
/usr/share/inkscape/tutorials/tutorial-tracing.es.svg
/usr/share/inkscape/tutorials/tutorial-tracing.eu.svg
/usr/share/inkscape/tutorials/tutorial-tracing.fa.svg
/usr/share/inkscape/tutorials/tutorial-tracing.fr.svg
/usr/share/inkscape/tutorials/tutorial-tracing.gl.svg
/usr/share/inkscape/tutorials/tutorial-tracing.hu.svg
/usr/share/inkscape/tutorials/tutorial-tracing.id.svg
/usr/share/inkscape/tutorials/tutorial-tracing.ja.svg
/usr/share/inkscape/tutorials/tutorial-tracing.nl.svg
/usr/share/inkscape/tutorials/tutorial-tracing.pl.svg
/usr/share/inkscape/tutorials/tutorial-tracing.pt.svg
/usr/share/inkscape/tutorials/tutorial-tracing.pt_BR.svg
/usr/share/inkscape/tutorials/tutorial-tracing.ru.svg
/usr/share/inkscape/tutorials/tutorial-tracing.sk.svg
/usr/share/inkscape/tutorials/tutorial-tracing.sl.svg
/usr/share/inkscape/tutorials/tutorial-tracing.svg
/usr/share/inkscape/tutorials/tutorial-tracing.vi.svg
/usr/share/inkscape/tutorials/tutorial-tracing.zh_TW.svg
/usr/share/inkscape/tutorials/tux.png
/usr/share/inkscape/ui/keybindings.rc
/usr/share/inkscape/ui/menus-bars.xml
/usr/share/inkscape/ui/style.css
/usr/share/inkscape/ui/toolbox.xml
/usr/share/inkscape/ui/units.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/inkscape/CMakeScripts_COPYING-CMAKE-SCRIPTS
/usr/share/package-licenses/inkscape/COPYING
/usr/share/package-licenses/inkscape/GPL2.txt
/usr/share/package-licenses/inkscape/cxxtest_COPYING
/usr/share/package-licenses/inkscape/src_libvpsc_COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/de/man1/inkscape.de.1
/usr/share/man/el/man1/inkscape.el.1
/usr/share/man/fr/man1/inkscape.fr.1
/usr/share/man/ja/man1/inkscape.ja.1
/usr/share/man/man1/inkscape.1
/usr/share/man/man1/inkscape.de.1
/usr/share/man/man1/inkscape.el.1
/usr/share/man/man1/inkscape.fr.1
/usr/share/man/man1/inkscape.ja.1
/usr/share/man/man1/inkscape.sk.1
/usr/share/man/man1/inkscape.zh_TW.1
/usr/share/man/man1/inkview.1
/usr/share/man/sk/man1/inkscape.ja.1
/usr/share/man/zh_TW/man1/inkscape.zh_TW.1

%files locales -f inkscape.lang
%defattr(-,root,root,-)

